name: Build and Lint
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push, pull_request]
jobs:
  Build-Lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm i

      - name: Run LINTER CHECK
        id: buildmf
        run: |
          OUTPUT=$(npm run format:check)
          echo "::set-output name=build_output::${OUTPUT}"

      - name: Check final status
        #        if: success()
        run: |
          echo "Build output: ${{ needs.buildmf.outputs.build_output }}"

      - name: Lint files
        run: npm run format

      - run: echo "ğŸ This job's status is ${{ job.status }}."
